### ISSUE TITLE
Syntax coloring breaks on second set of curly-braces

### ISSUE THREAD

**Issue by GeertJohan** [GiantToast/language-terraform#16] opened 2016-02-25 12:23 UTC
Given this line:
```terraform
template = "${file("${path.module}/my-file-name")}"
```

The syntax coloring breaks. If I remove `${path.module}` it works fine.

**Comment by tranberg** [comment] 2016-04-15 13:16
Is this still an issue? I can't reproduce it.

**Comment by GiantToast** [comment] 2016-04-15 17:27
I also tried it out and can no longer reproduce.  Closing issue.

**Closed by GiantToast** 2016-04-15 17:27 UTC
